import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { MyCustomFont } from "../../../../public/assets/fonts/fonts";
import "../../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Techtimize chatbot",
  description: "Generated by create next app",
};

export default function RootLayoutChat({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${MyCustomFont.variable} container mx-auto bg-white`}>
        <main className="bg-white h-screen">{children}</main>
      </body>
    </html>
  );
}
